let hasTierToQuery = false;
let queryType = "";
let config = {
    tier:{
        mac:{
            key1:"A-List Classic",
            key2:"MAC",
            checked:""
        },
        mea:{
            key1:"A-List",
            key2:"MEA",
            checked:""
        },
        mei:{
            key1:"Insider",
            key2:"MEI",
            checked:""
        },
        mep:{
            key1:"Premiere",
            key2:"MEP",
            checked:""
        },
        mpg:{
            key1:"PremiereGo",
            key2:"MPG",
            checked:""
        }
   },
   genre:"",
   member:{
       membership:"Member",
       activeStatus:"Active",
       age:"13+"
   },
   query:{
       split:1,
       dev1:"",
       dev2:"",
       sendlist:"",
       additionalFields:"",
   },
   optIn:"",
   amcMasterSupression:"",
   associateSupression:"",
   freshAddressExclude:"",
   engagement:"",
   complaintsRemoval:""
}
